"""
scan_libraries.py
-----------------
Scans all .py files in your project, finds every third-party import,
checks what version is installed, and outputs a requirements.txt.

Usage:
    python scan_libraries.py                  # scans current directory
    python scan_libraries.py D:/websites/new  # scans specific folder

Output:
    - Prints a table of all libraries + versions
    - Saves requirements.txt in the same folder as this script
"""

import ast
import os
import sys
import subprocess

# ── 1. Collect all import names from .py files ──────────────────────────────
project_dir = sys.argv[1] if len(sys.argv) > 1 else "."
print(f"Scanning: {os.path.abspath(project_dir)}\n")

imports = set()
scanned_files = []

for root, _, files in os.walk(project_dir):
    for f in files:
        if not f.endswith(".py"):
            continue
        path = os.path.join(root, f)
        try:
            source = open(path, encoding="utf-8").read()
            tree   = ast.parse(source)
            scanned_files.append(path)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        imports.add(alias.name.split(".")[0])
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        imports.add(node.module.split(".")[0])
        except Exception as e:
            print(f"  Could not parse {path}: {e}")

print(f"Files scanned: {len(scanned_files)}")
for f in scanned_files:
    print(f"  {f}")

# ── 2. Map import name → pip package name (they often differ) ───────────────
IMPORT_TO_PKG = {
    "sklearn":     "scikit-learn",
    "cv2":         "opencv-python",
    "PIL":         "Pillow",
    "yaml":        "PyYAML",
    "bs4":         "beautifulsoup4",
    "soundfile":   "soundfile",
    "sf":          "soundfile",
    "librosa":     "librosa",
    "pydub":       "pydub",
    "scipy":       "scipy",
    "numpy":       "numpy",
    "np":          "numpy",
    "torch":       "torch",
    "torchaudio":  "torchaudio",
    "torchvision": "torchvision",
    "matplotlib":  "matplotlib",
    "pandas":      "pandas",
    "nx":          "networkx",
    "requests":    "requests",
    "flask":       "Flask",
    "django":      "Django",
}

# ── 3. Standard library modules to skip ─────────────────────────────────────
STDLIB = {
    "os","sys","re","io","abc","ast","csv","copy","math","time","enum","json",
    "glob","uuid","random","shutil","string","struct","typing","hashlib",
    "logging","pathlib","argparse","tempfile","datetime","itertools","functools",
    "operator","collections","contextlib","subprocess","threading","multiprocessing",
    "unittest","warnings","inspect","traceback","signal","socket","http","urllib",
    "email","html","xml","zipfile","tarfile","gzip","bz2","lzma","pickle","shelve",
    "sqlite3","configparser","dataclasses","textwrap","pprint","queue","heapq",
    "builtins","types","weakref","gc","platform","ctypes","struct","array",
    "__future__","abc","cmath","decimal","fractions","statistics",
}

# ── 4. Look up version for each third-party import ──────────────────────────
def get_version(pkg_name):
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "show", pkg_name],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                if line.startswith("Version:"):
                    return line.split(":", 1)[1].strip()
    except Exception:
        pass
    return None

third_party = {}
not_found   = []

for imp in sorted(imports):
    if imp in STDLIB or imp.startswith("_") or not imp:
        continue

    pkg = IMPORT_TO_PKG.get(imp, imp)

    version = get_version(pkg)

    # If not found under mapped name, try raw import name
    if version is None and pkg != imp:
        version = get_version(imp)
        if version is not None:
            pkg = imp

    if version is not None:
        third_party[pkg] = version
    else:
        not_found.append(imp)

# ── 5. Print results ─────────────────────────────────────────────────────────
print("\n" + "=" * 50)
print("THIRD-PARTY LIBRARIES FOUND")
print("=" * 50)
print(f"  {'Package':<28} {'Version'}")
print(f"  {'-'*28} {'-'*10}")
for pkg, ver in sorted(third_party.items()):
    print(f"  {pkg:<28} {ver}")

if not_found:
    print(f"\n  Could not find via pip (may be stdlib or not installed):")
    for n in sorted(not_found):
        print(f"    {n}")

# ── 6. Save requirements.txt ─────────────────────────────────────────────────
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "requirements.txt")
with open(out_path, "w") as f:
    f.write("# Auto-generated by scan_libraries.py\n")
    f.write(f"# Project: {os.path.abspath(project_dir)}\n\n")
    for pkg, ver in sorted(third_party.items()):
        f.write(f"{pkg}=={ver}\n")

print("\n" + "=" * 50)
print(f"requirements.txt saved to:\n  {out_path}")
print("=" * 50)
print("\nTo install everything on a new machine:")
print("  pip install -r requirements.txt")